### ISSUE TITLE
Add if statements to Quil

### ISSUE THREAD

**Issue by stevenheidel** [rigetti/quil#7]
Instead of this:
```
MEASURE 0 ro
JUMP-WHEN ro @DELAY
RX(pi) 0
JUMP @END
LABEL DELAY
DELAY(60e-9) 0
LABEL END
```

We could have this:
```
MEASURE 0 ro
IF ro:
    RX(pi) 0
ELSE:
    DELAY(60e-9) 0
```

**Comment by stylewarning** [comment]
I would prefer to reserve this for a higher-level construct atop Quil; this breaks the "each line is a distinct instruction" "rule".

**Comment by stylewarning** [comment]
(trivia: the first version of quil had `IF`, `WHEN`, and `UNLESS`.)
